version: 2

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
            - run:
                name: ssh
                command: |
                  ssh ${USER_NAME}@${HOST_NAME} 'touch b.txt'
                  git clone https://github.com/nodenv/nodenv.git ~/.nodenv
                  echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.bashrc
                  echo 'eval "$(nodenv init -)"' >> ~/.bashrc
                  source ~/.bashrc
                  git clone https://github.com/nodenv/node-build.git $(nodenv root)/plugins/node-build

workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョ
    build_and_deploy:
        # build ジョブと deploy ジョブを登録
        jobs:
            - build
            - deploy:
                requires:
                    # 依存性あるから deploy ジョブより先に build ジョブを実行してね、
                    - build
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: circleci-project-setup
