version: 2

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
              # fingerprints:
              #   - 4b:21:d6:93:a1:c0:81:06:69:8e:2e:1e:ba:0c:5c:5e
            - run: ssh ${USER_NAME}@${HOST_NAME} 'touch fuga'
