version: 2

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
