version: 2.1

executors:
  default:
    docker:
      - image: circleci/alpine

jobs:
  build:
    executor: default
    steps:
      - run:
          name: now
          command: ssh ${USER_NAME}@${HOST_NAME} 'touch b.txt'
