version: 2.1

jobs:
    build:
        docker: 
        - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
        steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: echo "hello world" # `echo` コマンドを実行します

    deploy:
        docker: 
        - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
        steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
                - "b0:21:c9:8c:c7:b3:0c:92:58:d5:79:99:e4:10:8f:9b"
        - run: 
            name: ssh
            command: |
                ssh -p 22 $USER_NAME@$HOST_NAME 'touch b.txt'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: circleci-project-setup