version: 2

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
            - run:
                name: ssh
                command: |
                    ssh ${USER_NAME}@${HOST_NAME} 'touch 5.txt'
            - checkout
            - add_ssh_keys:
            - run:
                name: ssh2
                command: |
                    ssh ${USER_NAME}@${HOST_NAME} 'git clone https://github.com/nodenv/nodenv.git /home/ec2-user/.nodenv'
                    echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> /home/ec2-user/./home/ec2-user/
                    echo 'eval "$(nodenv init -)"' >> /home/ec2-user/.bashrc
                    source /home/ec2-user/.bashrc
                    git clone https://github.com/nodenv/node-build.git /home/ec2-user/.nodenv/plugins/node-build
                    sudo yum -y install curl
                    curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
                    sudo yum install -y nodejs
                    source ~/.bashrc
                    sudo chown ec2-user:ec2-user /home/ec2-user/.nodenv
                    source /home/ec2-user/.bashrc  nodenv install 16.8.0
                    nodenv global 16.8.0

workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョ
    build_and_deploy:
        # build ジョブと deploy ジョブを登録
        jobs:
            - build
            - deploy:
                requires:
                    # 依存性あるから deploy ジョブより先に build ジョブを実行してね、
                    - build
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: circleci-project-setup
