version: 2.1

jobs:
    build:
        docker: 
        - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
        steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: echo "hello world" # `echo` コマンドを実行します

    deploy:
        docker: 
        - image: circleci/node:4.8.2 # ジョブのコマンドが実行されるプライマリ コンテナ
        steps:
        - checkout
        - run:
            name: a
            command: touch a.txt

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: circleci-project-setup